_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
    WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/new_baselines/mask_rcnn_R_50_FPN_200ep_LSJ/42047638/model_final_89a8d3.pkl"
    MASK_ON: True
    RESNETS:
        DEPTH: 50
        NORM: "GN"
        STRIDE_IN_1X1: False
  
    ROI_BOX_HEAD:
        NAME: "FastRCNNConvFCHead"
        NUM_CONV: 4
        NUM_FC: 1
        NORM: "GN"
    ROI_MASK_HEAD:
        NORM: "GN"

    BACKBONE:
        FREEZE_AT: 0
        SFT_AT: 0   #must be <= 5 (5 resnet blocks, where 1 is the stem)
    ROI_HEADS:
        FREEZE: False # if True freeze ROI heads
        NUM_CLASSES: 1
        SCORE_THRESH_TEST: 0.9
        NMS_THRESH_TEST: 0.5
    FPN:
        NORM: "GN"
        FREEZE: False  # if True, applies SFT to same res block as SFT-ed backbone. Set False if only stem is SFT-ed
        JOINT_SFT: False
    RPN:
        FREEZE: False # If True, freeze RPN heads

DATALOADER:
  NUM_WORKERS: 2

INPUT:
  MIN_SIZE_TRAIN: (1024,)
  FORMAT: "BGR"

#SOLVER OPTIONS
SOLVER:
  MAX_ITER: 800
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 165
  BASE_LR: 0.001
  MOMENTUM: 0.9  

TEST:
  EVAL_PERIOD: 20

