_BASE_: "scratch_mask_rcnn_R_50_FPN_9x_gn.yaml" #"./Base-RCNN-FPN.yaml"
MODEL:
    WEIGHTS: "../../data/weights/wgisd_scratch_R50_bestval.pth" #weights of best model on WGISD 
    BACKBONE:
        FREEZE_AT: 0
        SFT_AT: 3
    ROI_HEADS:
        NUM_CLASSES: 1
        FREEZE: True # If True, freezes all ROI heads 
    FPN:
        FREEZE: True # if True, freeze all FPN blocks
        JOINT_SFT: False #If True, SFT jointly FPN based on no. at SFT_AT, if SFT_AT<=1, set to False
    RPN:
        FREEZE: True #If True, freezes Region Proposal Network

DATALOADER:
  NUM_WORKERS: 2

INPUT:
  MIN_SIZE_TRAIN: (1536,)
  MIN_SIZE_TEST: 0
  FORMAT: "BGR"

#SOLVER OPTIONS
SOLVER:
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 70
  BASE_LR: 0.01
  GAMMA: 0.5 
  # 3x schedule
  STEPS: (210000, 250000)
  MAX_ITER: 270000 

TEST:
  EVAL_PERIOD: 220

