_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
    WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/138205316/model_final_a3ec72.pkl"
    MASK_ON: True
    RESNETS:
        DEPTH: 101
        NORM: "GN"
        STRIDE_IN_1X1: False
  
    ROI_BOX_HEAD:
        NAME: "FastRCNNConvFCHead"
        NUM_CONV: 4
        NUM_FC: 1
        NORM: "GN"
    ROI_MASK_HEAD:
        NORM: "GN"

    BACKBONE:
        FREEZE_AT: 0
        SFT_AT: 0   #must be <= 5 (5 resnet blocks, where 1 is the stem)
    ROI_HEADS:
        FREEZE: False # if True freeze ROI heads
        NUM_CLASSES: 1
    FPN:
        NORM: "GN"
        FREEZE: False  # if True, applies SFT to same res block as SFT-ed backbone. Set False if only stem is SFT-ed
        JOINT_SFT: False
    RPN:
        FREEZE: False # If True, freeze RPN heads

DATALOADER:
  NUM_WORKERS: 2

INPUT:
  MIN_SIZE_TRAIN: (1024,)
  MIN_SIZE_TEST: 1024
  FORMAT: "BGR"

#SOLVER OPTIONS
SOLVER:
  IMS_PER_BATCH: 2
  WARMUP_ITERS: 70
  BASE_LR: 0.01
  GAMMA: 0.5
  # 3x schedule
  STEPS: (210000, 250000)
  MAX_ITER: 270000


TEST:
  EVAL_PERIOD: 220

